import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("tutorial screens are rendered from vanilla JS inside a mobile shell", async () => {
  const html = await readFile(new URL("index.html", root), "utf8");
  const css = await readFile(new URL("assets/styles.css", root), "utf8");
  const js = await readFile(new URL("assets/app.js", root), "utf8");

  assert.match(html, /期权入门/);
  assert.match(html, /id="app"/);
  assert.match(html, /assets\/styles\.css/);
  assert.match(html, /assets\/app\.js/);
  assert.match(js, /audienceContext/);
  assert.match(js, /交易期货/);
  assert.match(js, /期权新手/);
  assert.doesNotMatch(js, /background-card/);
  assert.doesNotMatch(js, /背景设定/);
  assert.doesNotMatch(js, /我平时也交易期货/);
  assert.doesNotMatch(js, /像素期货交易员/);
  assert.doesNotMatch(js, /像素期权助手/);
  assert.match(js, /期权新手/);
  assert.match(js, /期权老师/);
  assert.match(js, /speakerKind/);
  assert.match(js, /speaker-\$\{speakerKind\}/);
  assert.match(js, /avatar-\$\{speakerKind\}/);
  assert.match(js, /所以期权不是另一个期货/);
  assert.match(js, /它更像是给你的交易工具箱里/);
  assert.match(js, /我感觉还是有点抽象/);
  assert.match(js, /能举一些更直观的例子么/);
  assert.match(js, /为什么还要学股指期权/);
  assert.match(js, /我看涨就做多/);
  assert.match(js, /看跌就做空/);
  assert.match(js, /期权不是来替代期货/);
  assert.match(js, /不一定非要猜对方向/);
  assert.match(js, /波动会不会变大/);
  assert.match(js, /交易工具箱/);
  assert.match(js, /期货之外，期权多了什么？/);
  assert.match(js, /宽跨式：赚大波动/);
  assert.match(js, /messages/);
  assert.match(js, /currentMessageIndex/);
  assert.match(js, /visibleMessages/);
  assert.doesNotMatch(js, /utterances/);
  assert.doesNotMatch(js, /currentUtteranceIndex/);
  assert.doesNotMatch(js, /visibleUtterances/);
  assert.match(js, /advanceTutorial/);
  assert.match(js, /scrollDialogueToLatest/);
  assert.match(js, /lastDialogueScrollTop/);
  assert.match(js, /getCurrentDialogueScrollTop/);
  assert.match(js, /panel\.scrollTop = lastDialogueScrollTop/);
  assert.match(js, /scrollDurationMs = 900/);
  assert.match(js, /requestAnimationFrame/);
  assert.match(js, /lines:/);
  assert.match(js, /下一段/);
  assert.match(js, /看一个例子/);
  assert.match(js, /宽跨式/);
  assert.match(js, /4000/);
  assert.match(js, /4100 认购/);
  assert.match(js, /3900 认沽/);
  assert.match(js, /4180 以上赚钱/);
  assert.match(js, /3820 以下赚钱/);
  assert.match(js, /中间晃，亏权利金/);
  assert.match(js, /涨超 4180/);
  assert.match(js, /跌破 3820/);
  assert.match(js, /如果在这中间/);
  assert.match(js, /它怕的是不怎么动/);
  assert.match(js, /renderWideStrangleChart/);
  assert.match(js, /chart-card/);
  assert.match(js, /profit-zone up/);
  assert.match(js, /profit-zone down/);
  assert.match(js, /loss-zone/);
  assert.match(js, /activeHighlight/);
  assert.match(js, /做多怕它往下/);
  assert.match(js, /做空又怕它往上/);
  assert.match(js, /addEventListener\("click"/);
  assert.match(js, /pixel-avatar/);
  assert.match(css, /\.chart-card/);
  assert.match(css, /\.profit-zone/);
  assert.match(css, /\.loss-zone/);
  assert.match(css, /\.chart-threshold/);
  assert.match(css, /\.chart-price-path/);
  assert.match(css, /\.is-active/);
  assert.match(css, /height: 100%/);
  assert.match(css, /min-height: 0/);
  assert.match(css, /\.dialogue-panel/);
  assert.match(css, /overflow-y: auto/);
  assert.match(css, /scroll-behavior: auto/);
  assert.match(css, /\.dialogue-card\.student/);
  assert.match(css, /\.dialogue-card\.teacher/);
  assert.match(css, /grid-template-columns: 54px minmax\(0, 1fr\)/);
  assert.match(css, /grid-template-columns: minmax\(0, 1fr\) 54px/);
  assert.match(css, /\.avatar-student/);
  assert.match(css, /\.avatar-teacher/);
  assert.match(css, /\.speaker-student/);
  assert.match(css, /\.speaker-teacher/);
  assert.match(css, /padding: 14px 16px 16px/);
  assert.match(css, /\.topbar\s*\{\s*padding: 4px 2px 8px/s);
  assert.match(css, /font-size: 1\.12rem/);
  assert.match(css, /\.screen\s*\{[^}]*gap: 8px/s);
  assert.match(css, /\.screen-copy\s*\{\s*padding-top: 0/s);
  assert.match(css, /font-size: 1\.18rem/);
  assert.match(css, /white-space: nowrap/);
  assert.match(css, /text-overflow: ellipsis/);
  assert.match(css, /max-width: 430px/);
  assert.match(css, /min-height: 100svh/);
});
